# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsp" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "7b2b3cc06dbaa5ca48c58abe5dd36e2684f96dd9170d94d362136a0faa86a12e"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03f8dce4c1c37d3a94751ada3be18536151369cd56a9d3dfd9066980b18e11e9"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cda89cdaadadf3addc9db807570b78cbc124a1bc2a02fa94cc575ff9849c9456"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d19463597c948fee36fa12d2700df80a0c5f1f55b6f22863b08657358e3ddca0"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "awsp"
  desc "AWS profile switcher with SSO status, PKCE login and an MCP server for AI agents"
  homepage "https://github.com/kagamirror123/awsp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsp"
  bash_completion "completions/awsp.bash"
  fish_completion "completions/awsp.fish"
  zsh_completion "completions/awsp.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    シェル連携を設定すると awsp <profile> が親シェルに反映されます:
      zsh : echo 'eval "$(awsp init zsh)"' >> ~/.zshrc
      bash: echo 'eval "$(awsp init bash)"' >> ~/.bashrc
      fish: echo 'awsp init fish | source' >> ~/.config/fish/config.fish
  EOS
end
