# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsp" do
  version "0.11.1"

  on_macos do
    on_arm do
      sha256 "098277b64728b58e5e4fd12c3f5b7facb39f522f5d3950fde3b153fbd8f639e9"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc061ac25a557f041fdbe75737c4b733de4afac676353f65eb7cbb533c221622"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "70a023e6701c3bac7bd79ef41a0129ca3efc57e29789b70841dc4f8e5d038856"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a454c9502280475bec181317ec81263850d35fb8c91be119a832ebdd0fd2091e"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "awsp"
  desc "AWS profile switcher with SSO status, PKCE login and an MCP server for AI agents"
  homepage "https://github.com/kagamirror123/awsp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    シェル連携を設定すると awsp <profile> が親シェルに反映されます:
      zsh : echo 'eval "$(awsp init zsh)"' >> ~/.zshrc
      bash: echo 'eval "$(awsp init bash)"' >> ~/.bashrc
      fish: echo 'awsp init fish | source' >> ~/.config/fish/config.fish
  EOS
end
