# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsp" do
  version "0.12.1"

  on_macos do
    on_arm do
      sha256 "ee4075c4d6df220b51e1b01c5f163d833f7e541a8c2332b4f5ba5df23fb36ff2"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ffd5a08adf43576a945885244d8d3f06d94126ed026eeea035173abfc15cedd7"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "123d041636a988d8ee09dcc063cee1733c98089eb8c56c03a01d6402f06945fa"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f642ad70f325eb8c368f9ff9aa6f006f81e08e474858e24494c2e52182dba988"
      url "https://github.com/kagamirror123/awsp/releases/download/v#{version}/awsp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "awsp"
  desc "AWS profile switcher with SSO status, PKCE login and an MCP server for AI agents"
  homepage "https://github.com/kagamirror123/awsp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsp"
  bash_completion "completions/awsp.bash"
  fish_completion "completions/awsp.fish"
  zsh_completion "completions/awsp.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    シェル連携を設定すると awsp <profile> が親シェルに反映されます:
      zsh : echo 'eval "$(awsp init zsh)"' >> ~/.zshrc
      bash: echo 'eval "$(awsp init bash)"' >> ~/.bashrc
      fish: echo 'awsp init fish | source' >> ~/.config/fish/config.fish
  EOS
end
